# Generated by Django 3.1 on 2020-08-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_user_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.CharField(default='Undefined', max_length=30),
        ),
        migrations.AlterField(
            model_name='education',
            name='name',
            field=models.CharField(default='Undefined', max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='study_from',
            field=models.CharField(default='Undefined', max_length=30),
        ),
        migrations.AlterField(
            model_name='education',
            name='study_till',
            field=models.CharField(default='Undefined', max_length=30),
        ),
        migrations.AlterField(
            model_name='education',
            name='title',
            field=models.CharField(default='Undefined', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='completion',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='Undefined', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='Undefined', max_length=30),
        ),
        migrations.AlterField(
            model_name='work',
            name='c_name',
            field=models.CharField(default='Undefined', max_length=30),
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.CharField(default='Undefined', max_length=30),
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(default='Undefined', max_length=30),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_from',
            field=models.CharField(default='Undefined', max_length=30),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_till',
            field=models.CharField(default='Undefined', max_length=30),
        ),
    ]
