# Generated by Django 3.1 on 2020-08-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_auto_20200822_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='resume',
            field=models.FileField(null=True, upload_to='resume/'),
        ),
    ]
