# Generated by Django 3.1 on 2020-08-22 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_userprofile_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
